// <auto-generated />
using FilmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmAPI.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20231002072914_newDb")]
    partial class newDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CharacterMovie");
                });

            modelBuilder.Entity("FilmAPI.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Ring-Bearer",
                            FullName = "Frodo Baggins",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/lotr/images/3/32/Frodo_%28FotR%29.png/revision/latest?cb=20221006065757"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Strider",
                            FullName = "Aragorn",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/warner-bros-entertainment/images/6/6a/94E54497-FAC0-4332-9531-27A0A5962043.jpeg/revision/latest?cb=20190108035325"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Gollum",
                            FullName = "Sméagol",
                            Gender = "Male",
                            PictureUrl = "https://pyxis.nymag.com/v1/imgs/5d4/f6e/c6aeaba039ba41d69a9dbce8c3523ec471-11-gollum.rsquare.w700.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Alias = "The Chosen One",
                            FullName = "Luke Skywalker",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/starwars/images/2/20/LukeTLJ.jpg/revision/latest?cb=20170927045449"
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Ben Kenobi",
                            FullName = "Obi-Wan Kenobi",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/starwars/images/4/4e/ObiWanHS-SWE.jpg/revision/latest?cb=20111126060943"
                        },
                        new
                        {
                            Id = 6,
                            Alias = "Darth Vader",
                            FullName = "Anakin Skywalker",
                            Gender = "Male",
                            PictureUrl = "https://imageio.forbes.com/specials-images/imageserve/6090f7f251c9c6c605e612fc/Darth-Vader/0x0.jpg?format=jpg&crop=3127,1759,x0,y33,safe&width=960"
                        },
                        new
                        {
                            Id = 7,
                            Alias = "The Boy Who Lived",
                            FullName = "Harry James Potter",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/harrypotter/images/0/0e/Harry_James_Potter.jpg/revision/latest?cb=20150808063507"
                        },
                        new
                        {
                            Id = 8,
                            Alias = "Lord Voldemort",
                            FullName = "Tom Marvolo Riddle",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/harrypotter/images/4/4b/VoldemortHeadshot_DHP1.png/revision/latest?cb=20161223175148"
                        },
                        new
                        {
                            Id = 9,
                            Alias = "Professor Dumbledore",
                            FullName = "Albus Percival Wulfric Brian Dumbledore",
                            Gender = "Male",
                            PictureUrl = "https://static.wikia.nocookie.net/harrypotter/images/5/5e/Albus_Dumbledore_%28HBP_promo%29_2.jpg/revision/latest?cb=20150808063507"
                        });
                });

            modelBuilder.Entity("FilmAPI.Data.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The epic fantasy franchise based on J.R.R. Tolkien's novels.",
                            Name = "Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The iconic space opera franchise created by George Lucas.",
                            Name = "Star Wars"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The fantasy franchise based on J.K. Rowling's novels.",
                            Name = "Harry Potter"
                        });
                });

            modelBuilder.Entity("FilmAPI.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Peter Jackson",
                            FranchiseId = 1,
                            Genre = "Epic fantasy",
                            PictureUrl = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
                            ReleaseYear = 2001,
                            Title = "Fellowship of the ring",
                            TrailerUrl = "https://www.youtube.com/watch?v=V75dMMIW2B4&ab_channel=Movieclips"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Peter Jackson",
                            FranchiseId = 1,
                            Genre = "Epic fantasy",
                            PictureUrl = "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg",
                            ReleaseYear = 2002,
                            Title = "The Two Towers",
                            TrailerUrl = "https://www.youtube.com/watch?v=hYcw5ksV8YQ"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Peter Jackson",
                            FranchiseId = 1,
                            Genre = "Epic fantasy",
                            PictureUrl = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            ReleaseYear = 2003,
                            Title = "The Return of the King",
                            TrailerUrl = "https://www.youtube.com/watch?v=r5X-hFf6Bwo"
                        },
                        new
                        {
                            Id = 4,
                            Director = "George Lucas",
                            FranchiseId = 2,
                            Genre = "Space opera",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
                            ReleaseYear = 1977,
                            Title = "Star Wars Episode IV: A New Hope",
                            TrailerUrl = "https://www.youtube.com/watch?v=1g3_CFmnU7k"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Irvin Kershner",
                            FranchiseId = 2,
                            Genre = "Space opera",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/3/3c/SW_-_Empire_Strikes_Back.jpg",
                            ReleaseYear = 1980,
                            Title = "Star Wars Episode V: The Empire Strikes Back",
                            TrailerUrl = "https://www.youtube.com/watch?v=JNwNXF9Y6kY"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Richard Marquand",
                            FranchiseId = 2,
                            Genre = "Space opera",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/b/b2/ReturnOfTheJediPoster1983.jpg",
                            ReleaseYear = 1983,
                            Title = "Star Wars Episode VI: Return of the Jedi",
                            TrailerUrl = "https://www.youtube.com/watch?v=7L8p7_SLzvU"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Chris Columbus",
                            FranchiseId = 3,
                            Genre = "Fantasy",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/b/bf/Harry_Potter_and_the_Philosopher%27s_Stone_posters.JPG",
                            ReleaseYear = 2001,
                            Title = "Harry Potter and the Philosopher's Stone",
                            TrailerUrl = "https://www.youtube.com/watch?v=VyHV0BRtdxo"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Chris Columbus",
                            FranchiseId = 3,
                            Genre = "Fantasy",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/c/c0/Harry_Potter_and_the_Chamber_of_Secrets_movie.jpg",
                            ReleaseYear = 2002,
                            Title = "Harry Potter and the Chamber of Secrets",
                            TrailerUrl = "https://www.youtube.com/watch?v=1bq0qff4iF8"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Alfonso Cuarón",
                            FranchiseId = 3,
                            Genre = "Fantasy",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/b/bc/Prisoner_of_azkaban_UK_poster.jpg",
                            ReleaseYear = 2004,
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            TrailerUrl = "https://www.youtube.com/watch?v=lAxgztbYDbs"
                        },
                        new
                        {
                            Id = 10,
                            Director = "Mike Newell",
                            FranchiseId = 3,
                            Genre = "Fantasy",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/en/c/c9/Harry_Potter_and_the_Goblet_of_Fire_Poster.jpg",
                            ReleaseYear = 2005,
                            Title = "Harry Potter and the Goblet of Fire",
                            TrailerUrl = "https://www.youtube.com/watch?v=PFWAOnvMd1Q"
                        });
                });

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.HasOne("FilmAPI.Data.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Data.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmAPI.Data.Models.Movie", b =>
                {
                    b.HasOne("FilmAPI.Data.Models.Franchise", "Franchise")
                        .WithMany("Movies")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("FilmAPI.Data.Models.Franchise", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
